version: '3.8'
services:
  #API Gateway
  api-gateway:
    container_name: api-gateway
    build: api-gateway/
    restart: always
    ports:
      - "8004:8004"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEuRL_DEFAULTZONE=http://eureka-server:8761/eureka/

  #Eureka server
  eureka-server:
    container_name: eureka-server
    build: eureka-server/
    restart: always
    ports:
      - "8761:8761"

  payment-mysql:
    container_name: payment-mysql
    image: mysql:latest
    restart: always
    ports:
      - "3301:3301"
    environment:
      MYSQL_ROOT_PASSWORD: mysql@123
      MYSQL_DATABASE: orders
    networks:
      - mynetwork

  payment-service:
    container_name: payment-service
    build: payment-service/
    restart: always
    ports:
      - "8087:8087"
    depends_on:
      - payment-mysql
      - eureka-server
      - api-gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://payment-mysql:3301/orders?autoReconnect=true&useSSL=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql@123
      - EUREKA_CLIENT_SERVICEuRL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - mynetwork

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mynetwork

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - mynetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - mynetwork

  parking-provider-service:
    container_name: parking-provider-service
    build: parking-provider-service/
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - api-gateway
      - elasticsearch
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ELASTICSEARCH_URL=elasticsearch:9200
      - SPRING_DATA_ELASTICSEARCH_CLUSTERNODES=elasticsearch:9200
      - SPRING_DATA_ELASTICSEARCH_CLUSTERNAME=elasticsearch
      - SPRING_KAFKA_BOOTSTRAPSERVERS=broker:29092
      - EUREKA_CLIENT_SERVICEuRL_DEFAULTZONE=http://eureka-server:8761/eureka/
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge