server:
  port: 8081
  
spring:
  application:
    name:  API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: CUSTOM-BOT-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/bot/**

        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/**

        - id: parking-provider-service
          uri: http://localhost:8085
          predicates:
            - Path=/parking-area/**,/parking-spot/**,/price-service/**

        - id: parking-space-booking
          uri: http://localhost:8086
          predicates:
            - Path=/Booking/**,/producer-app/**

        - id: payment-service
          uri: http://localhost:8087
          predicates:
            - Path=/user/**

        - id: product-webapp
          uri: http://localhost:8088
          predicates:
            - Path=/webapp/**

        - id: review-service
          uri: http://localhost:8089
          predicates:
            - Path=/reviewAndRating/**

        - id: user-authentication-management
          uri: http://localhost:8090
          predicates:
            - Path=/auth/**,/customer/**,/provider/**





  
  
  
  