FROM openjdk:11
COPY ./target/UserAuthenticationManagementApplication-0.0.1-SNAPSHOT.jar UserAuthenticationManagementApplication-0.0.1-SNAPSHOT.jar
EXPOSE 8090
CMD ["java", "-jar", "UserAuthenticationManagementApplication-0.0.1-SNAPSHOT.jar"]